### ISSUE TITLE
Call workflow doesn't work

### ISSUE THREAD

**Issue by Tom-van-Woudenberg** [TeachBooks/learn-python#5]
I've run the old workflow again so the book is back online @guin0x  and @rlanzafame , for some reason the call workflow doesn't work @severinbratus  is looking into it

**Comment by severinbratus** [comment]
I believe this is because the newer workflow uses the `teachbooks` package, which is not in the requirements.txt, so the build never happens, and this is why the artifacts are empty. @guinox  can I copy over https://github.com/TeachBooks/template/blob/main/requirements.txt to https://github.com/TeachBooks/learn-python/blob/main/requirements.txt ?

**Comment by Tom-van-Woudenberg** [comment]
That seems true indeed: https://github.com/TeachBooks/learn-python/actions/runs/8844713877/job/24295463669#step:7:34. Although before that gave another error, when building the book it would give a critical error it couldn't find teachbooks and abort. That seems better

**Comment by Tom-van-Woudenberg** [comment]
I've updated the requirements files and removed the old workflow. I"m still curious why it gave a non-critical workflow

**Comment by guin0x** [comment]
I'm going to close the issue as I see the book is online again.
